openapi: 3.0.3
info:
  title: Raygun applications deployments API
  version: '3.0'
  description: This is a visual representation of the Raygun API V3 specification.<br> To find out more details and how to get started, you can head over to the <a href='https://raygun.com/documentation/product-guides/public-api/' target='_blank'>documentation</a>.
  contact:
    name: Raygun Support
    email: support@raygun.com
servers:
- url: https://api.raygun.com/v3
  description: ''
security:
- personal_access_token: []
tags:
- name: deployments
paths:
  /applications/{application-identifier}/deployments:
    get:
      summary: List Deployments for an Application
      operationId: list-deployments
      description: Returns a list of deployments for the specified application
      security:
      - personal_access_token:
        - deployments:read
      tags:
      - deployments
    post:
      summary: Create Deployment
      operationId: create-deployment
      description: Create a deployment for the specified application
      security:
      - personal_access_token:
        - deployments:write
      tags:
      - deployments
  /applications/{application-identifier}/deployments/latest:
    get:
      summary: Get the Latest Deployment
      operationId: get-latest-deployment
      description: Returns the latest deployment
      security:
      - personal_access_token:
        - deployments:read
      tags:
      - deployments
  /applications/{application-identifier}/deployments/{deployment-identifier}:
    get:
      summary: Get Deployment by Identifier
      operationId: get-deployment
      description: Returns a single deployment by identifier
      security:
      - personal_access_token:
        - deployments:read
      tags:
      - deployments
    delete:
      summary: Delete Deployment
      operationId: delete-deployment
      description: Delete a deployment
      security:
      - personal_access_token:
        - deployments:write
      tags:
      - deployments
    patch:
      summary: Update Deployment Details
      operationId: update-deployment
      description: Update the details of a deployment
      security:
      - personal_access_token:
        - deployments:write
      tags:
      - deployments
  /applications/{application-identifier}/deployments/latest/error-groups:
    get:
      summary: List Error Groups From the Latest Deployment
      operationId: list-error-groups-from-latest-deployment
      description: Returns a list of error groups from the latest deployment
      security:
      - personal_access_token:
        - cr.errors:read
      tags:
      - deployments
  /applications/{application-identifier}/deployments/{deployment-identifier}/error-groups:
    get:
      summary: List Error Groups From a Deployment
      operationId: list-error-groups-from-deployment
      description: Returns a list of error groups from the specified deployment
      security:
      - personal_access_token:
        - cr.errors:read
      tags:
      - deployments
  /applications/api-key/{api-key}/deployments:
    post:
      summary: Create Deployment With Api Key
      operationId: create-deployment-api-key
      description: Create a deployment for an application with the specified api key
      security:
      - personal_access_token:
        - deployments:write
      tags:
      - deployments
  /applications/{application-identifier}/deployments/{deployment-identifier}/reprocess-commits:
    post:
      summary: Reprocess Deployment Commits
      operationId: reprocess-deployment-commits
      description: Reprocess commits for a deployment
      security:
      - personal_access_token:
        - deployments:write
      tags:
      - deployments
components:
  securitySchemes:
    personal_access_token:
      type: http
      scheme: bearer
      description: 'Personal Access Token authorization using the Bearer scheme. Example: `Authorization: Bearer {token}`'
