naftiko: 1.0.0-alpha2
info:
  label: "Raygun Public API \u2014 Deployments"
  description: "Raygun Public API \u2014 Deployments business capability. 10 operations against the Raygun v3 REST API."
  tags:
  - Raygun
  - Deployments
  - Observability
  created: '2026-05-25'
  modified: '2026-05-25'
binds:
- namespace: env
  keys:
    RAYGUN_PERSONAL_ACCESS_TOKEN: RAYGUN_PERSONAL_ACCESS_TOKEN
capability:
  consumes:
  - type: http
    namespace: deployments-deployments
    baseUri: https://api.raygun.com/v3
    description: "Raygun Public API \u2014 Deployments. Self-contained Naftiko capability."
    resources:
    - name: applications-application-identifier-deployments
      path: /applications/{application-identifier}/deployments
      operations:
      - name: list-deployments
        method: GET
        description: List Deployments for an Application
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: null
          in: query
          type: string
          description: ''
          required: false
        - name: null
          in: query
          type: string
          description: ''
          required: false
        - name: orderby
          in: query
          type: array
          description: Order items by property values
          required: false
      - name: create-deployment
        method: POST
        description: Create Deployment
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: false
    - name: applications-application-identifier-deployments-latest
      path: /applications/{application-identifier}/deployments/latest
      operations:
      - name: get-latest-deployment
        method: GET
        description: Get the Latest Deployment
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters: []
    - name: applications-application-identifier-deployments-deployment-identifier
      path: /applications/{application-identifier}/deployments/{deployment-identifier}
      operations:
      - name: get-deployment
        method: GET
        description: Get Deployment by Identifier
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters: []
      - name: delete-deployment
        method: DELETE
        description: Delete Deployment
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters: []
      - name: update-deployment
        method: PATCH
        description: Update Deployment Details
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: false
    - name: applications-application-identifier-deployments-latest-error-groups
      path: /applications/{application-identifier}/deployments/latest/error-groups
      operations:
      - name: list-error-groups-from-latest-deployment
        method: GET
        description: List Error Groups From the Latest Deployment
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: null
          in: query
          type: string
          description: ''
          required: false
        - name: null
          in: query
          type: string
          description: ''
          required: false
        - name: filter
          in: query
          type: string
          description: Filter items by an expression. Currently supports filtering by the virtual property `state`, which
            can be `new`, `stillOccurring`, or `regressed`
          required: false
        - name: orderby
          in: query
          type: array
          description: Order items by property values
          required: false
    - name: applications-application-identifier-deployments-deployment-identifier-error-groups
      path: /applications/{application-identifier}/deployments/{deployment-identifier}/error-groups
      operations:
      - name: list-error-groups-from-deployment
        method: GET
        description: List Error Groups From a Deployment
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: null
          in: query
          type: string
          description: ''
          required: false
        - name: null
          in: query
          type: string
          description: ''
          required: false
        - name: filter
          in: query
          type: string
          description: Filter items by an expression. Currently supports filtering by the virtual property `state`, which
            can be `new`, `stillOccurring`, or `regressed`
          required: false
        - name: orderby
          in: query
          type: array
          description: Order items by property values
          required: false
    - name: applications-api-key-api-key-deployments
      path: /applications/api-key/{api-key}/deployments
      operations:
      - name: create-deployment-api-key
        method: POST
        description: Create Deployment With Api Key
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: false
    - name: applications-application-identifier-deployments-deployment-identifier-reprocess-commits
      path: /applications/{application-identifier}/deployments/{deployment-identifier}/reprocess-commits
      operations:
      - name: reprocess-deployment-commits
        method: POST
        description: Reprocess Deployment Commits
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters: []
    authentication:
      type: bearer
      value: '{{env.RAYGUN_PERSONAL_ACCESS_TOKEN}}'
      placement: header
  exposes:
  - type: rest
    namespace: deployments-deployments-rest
    port: 8080
    description: REST adapter for Raygun Deployments.
    resources:
    - path: /v3/applications/{application-identifier}/deployments
      name: applications-application-identifier-deployments
      description: REST surface for applications-application-identifier-deployments.
      operations:
      - method: GET
        name: list-deployments
        description: List Deployments for an Application
        call: deployments-deployments.list-deployments
        with:
          null: rest.query.None
          orderby: rest.query.orderby
        outputParameters:
        - type: object
          mapping: $.
      - method: POST
        name: create-deployment
        description: Create Deployment
        call: deployments-deployments.create-deployment
        with:
          body: rest.body
        outputParameters:
        - type: object
          mapping: $.
    - path: /v3/applications/{application-identifier}/deployments/latest
      name: applications-application-identifier-deployments-latest
      description: REST surface for applications-application-identifier-deployments-latest.
      operations:
      - method: GET
        name: get-latest-deployment
        description: Get the Latest Deployment
        call: deployments-deployments.get-latest-deployment
        with: {}
        outputParameters:
        - type: object
          mapping: $.
    - path: /v3/applications/{application-identifier}/deployments/{deployment-identifier}
      name: applications-application-identifier-deployments-deployment-identifier
      description: REST surface for applications-application-identifier-deployments-deployment-identifier.
      operations:
      - method: GET
        name: get-deployment
        description: Get Deployment by Identifier
        call: deployments-deployments.get-deployment
        with: {}
        outputParameters:
        - type: object
          mapping: $.
      - method: DELETE
        name: delete-deployment
        description: Delete Deployment
        call: deployments-deployments.delete-deployment
        with: {}
        outputParameters:
        - type: object
          mapping: $.
      - method: PATCH
        name: update-deployment
        description: Update Deployment Details
        call: deployments-deployments.update-deployment
        with:
          body: rest.body
        outputParameters:
        - type: object
          mapping: $.
    - path: /v3/applications/{application-identifier}/deployments/latest/error-groups
      name: applications-application-identifier-deployments-latest-error-groups
      description: REST surface for applications-application-identifier-deployments-latest-error-groups.
      operations:
      - method: GET
        name: list-error-groups-from-latest-deployment
        description: List Error Groups From the Latest Deployment
        call: deployments-deployments.list-error-groups-from-latest-deployment
        with:
          null: rest.query.None
          filter: rest.query.filter
          orderby: rest.query.orderby
        outputParameters:
        - type: object
          mapping: $.
    - path: /v3/applications/{application-identifier}/deployments/{deployment-identifier}/error-groups
      name: applications-application-identifier-deployments-deployment-identifier-error-groups
      description: REST surface for applications-application-identifier-deployments-deployment-identifier-error-groups.
      operations:
      - method: GET
        name: list-error-groups-from-deployment
        description: List Error Groups From a Deployment
        call: deployments-deployments.list-error-groups-from-deployment
        with:
          null: rest.query.None
          filter: rest.query.filter
          orderby: rest.query.orderby
        outputParameters:
        - type: object
          mapping: $.
    - path: /v3/applications/api-key/{api-key}/deployments
      name: applications-api-key-api-key-deployments
      description: REST surface for applications-api-key-api-key-deployments.
      operations:
      - method: POST
        name: create-deployment-api-key
        description: Create Deployment With Api Key
        call: deployments-deployments.create-deployment-api-key
        with:
          body: rest.body
        outputParameters:
        - type: object
          mapping: $.
    - path: /v3/applications/{application-identifier}/deployments/{deployment-identifier}/reprocess-commits
      name: applications-application-identifier-deployments-deployment-identifier-reprocess-commits
      description: REST surface for applications-application-identifier-deployments-deployment-identifier-reprocess-commits.
      operations:
      - method: POST
        name: reprocess-deployment-commits
        description: Reprocess Deployment Commits
        call: deployments-deployments.reprocess-deployment-commits
        with: {}
        outputParameters:
        - type: object
          mapping: $.
  - type: mcp
    namespace: deployments-deployments-mcp
    port: 9090
    transport: http
    description: MCP adapter for Raygun Deployments.
    tools:
    - name: raygun-list-deployments
      description: List Deployments for an Application
      hints:
        readOnly: true
        destructive: false
        idempotent: true
      call: deployments-deployments.list-deployments
      with:
        null: tools.None
        orderby: tools.orderby
      outputParameters:
      - type: object
        mapping: $.
    - name: raygun-create-deployment
      description: Create Deployment
      hints:
        readOnly: false
        destructive: false
        idempotent: false
      call: deployments-deployments.create-deployment
      with:
        body: tools.body
      outputParameters:
      - type: object
        mapping: $.
    - name: raygun-get-latest-deployment
      description: Get the Latest Deployment
      hints:
        readOnly: true
        destructive: false
        idempotent: true
      call: deployments-deployments.get-latest-deployment
      with: {}
      outputParameters:
      - type: object
        mapping: $.
    - name: raygun-get-deployment
      description: Get Deployment by Identifier
      hints:
        readOnly: true
        destructive: false
        idempotent: true
      call: deployments-deployments.get-deployment
      with: {}
      outputParameters:
      - type: object
        mapping: $.
    - name: raygun-delete-deployment
      description: Delete Deployment
      hints:
        readOnly: false
        destructive: true
        idempotent: true
      call: deployments-deployments.delete-deployment
      with: {}
      outputParameters:
      - type: object
        mapping: $.
    - name: raygun-update-deployment
      description: Update Deployment Details
      hints:
        readOnly: false
        destructive: false
        idempotent: false
      call: deployments-deployments.update-deployment
      with:
        body: tools.body
      outputParameters:
      - type: object
        mapping: $.
    - name: raygun-list-error-groups-from-latest-deployment
      description: List Error Groups From the Latest Deployment
      hints:
        readOnly: true
        destructive: false
        idempotent: true
      call: deployments-deployments.list-error-groups-from-latest-deployment
      with:
        null: tools.None
        filter: tools.filter
        orderby: tools.orderby
      outputParameters:
      - type: object
        mapping: $.
    - name: raygun-list-error-groups-from-deployment
      description: List Error Groups From a Deployment
      hints:
        readOnly: true
        destructive: false
        idempotent: true
      call: deployments-deployments.list-error-groups-from-deployment
      with:
        null: tools.None
        filter: tools.filter
        orderby: tools.orderby
      outputParameters:
      - type: object
        mapping: $.
    - name: raygun-create-deployment-api-key
      description: Create Deployment With Api Key
      hints:
        readOnly: false
        destructive: false
        idempotent: false
      call: deployments-deployments.create-deployment-api-key
      with:
        body: tools.body
      outputParameters:
      - type: object
        mapping: $.
    - name: raygun-reprocess-deployment-commits
      description: Reprocess Deployment Commits
      hints:
        readOnly: false
        destructive: false
        idempotent: false
      call: deployments-deployments.reprocess-deployment-commits
      with: {}
      outputParameters:
      - type: object
        mapping: $.
